version: '3.12.12'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' # Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  rabbitmq-data:
